In [ ]:
# Imports & Connection
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:Vivek123@localhost:5432/retail_dw"
)

print("Connected Successfully")

Connected Successfully

In [2]:
# Orders Count Validation
query = """
SELECT COUNT(*) as total_orders
FROM raw.orders
"""

pd.read_sql(query, engine)

   total_orders
0         99441

In [3]:
# Revenue Validation
query = """
SELECT ROUND(SUM(payment_value),2) as total_revenue
FROM raw.payments
"""

pd.read_sql(query, engine)

   total_revenue
0    16008872.12

In [4]:
# State Revenue Validation
query = """
SELECT *
FROM analytics.fct_state_revenue
ORDER BY total_revenue DESC
LIMIT 10
"""

pd.read_sql(query, engine)

  customer_state  total_revenue
0             SP     5998226.96
1             RJ     2144379.69
2             MG     1872257.26
3             RS      890898.54
4             PR      811156.38
5             SC      623086.43
6             BA      616645.82
7             DF      355141.08
8             GO      350092.31
9             ES      325967.55

In [5]:
# Monthly Revenue Validation
query = """
SELECT *
FROM analytics.fct_monthly_revenue
ORDER BY year, month
"""

pd.read_sql(query, engine)

      year  month  total_revenue
0   2016.0    9.0         252.24
1   2016.0   10.0       59090.48
2   2016.0   12.0          19.62
3   2017.0    1.0      138488.04
4   2017.0    2.0      291908.01
5   2017.0    3.0      449863.60
6   2017.0    4.0      417788.03
7   2017.0    5.0      592918.82
8   2017.0    6.0      511276.38
9   2017.0    7.0      592382.92
10  2017.0    8.0      674396.32
11  2017.0    9.0      727762.45
12  2017.0   10.0      779677.88
13  2017.0   11.0     1194882.80
14  2017.0   12.0      878401.48
15  2018.0    1.0     1115004.18
16  2018.0    2.0      992463.34
17  2018.0    3.0     1159652.12
18  2018.0    4.0     1160785.48
19  2018.0    5.0     1153982.15
20  2018.0    6.0     1023880.50
21  2018.0    7.0     1066540.75
22  2018.0    8.0     1022425.32
23  2018.0    9.0        4439.54
24  2018.0   10.0         589.67

In [6]:
# Order Status Validation
query = """
SELECT *
FROM analytics.fct_order_status
ORDER BY total_orders DESC
"""

pd.read_sql(query, engine)

  order_status  total_orders
0    delivered         96478
1      shipped          1107
2     canceled           625
3  unavailable           609
4     invoiced           314
5   processing           301
6      created             5
7     approved             2